### ISSUE TITLE
Consider merging with Graphviz.jl

### ISSUE THREAD

**Issue by abelsiqueira** [jhidding/DotLang.jl#3]
Hi @jhidding, thanks for the package. I was thinking if it makes sense to try to merge with https://github.com/JuliaGraphs/GraphViz.jl, if they are interested in sharing control. It looks like they are not maintaining the package.

The goals seem different: they focus on directly using the dot language and you focus on a user-friendly API. So having a single package that does both might be good, and it doesn't look too heavy.

**Comment by jhidding** [comment]
With the inclusion of `Graphviz_jll` as a dependency, there is no need for the old `GraphViz.jl` anymore.
